// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDudk0G-cvMu10HEy2o7Brt7cDI8XvmjTU',
    appId: '1:37223953098:web:d55cb317ac62d043113a33',
    messagingSenderId: '37223953098',
    projectId: 'surfspot-884c9',
    authDomain: 'surfspot-884c9.firebaseapp.com',
    storageBucket: 'surfspot-884c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-gbkP7sRaJnvcGf25cSrC0n6YtvmU7v0',
    appId: '1:37223953098:android:c78d4944cefca173113a33',
    messagingSenderId: '37223953098',
    projectId: 'surfspot-884c9',
    storageBucket: 'surfspot-884c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHu89jF7F5w0ogetIcCC1Mku02iq2va6M',
    appId: '1:37223953098:ios:0a867360bd1ab719113a33',
    messagingSenderId: '37223953098',
    projectId: 'surfspot-884c9',
    storageBucket: 'surfspot-884c9.firebasestorage.app',
    iosBundleId: 'com.example.surfspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHu89jF7F5w0ogetIcCC1Mku02iq2va6M',
    appId: '1:37223953098:ios:0a867360bd1ab719113a33',
    messagingSenderId: '37223953098',
    projectId: 'surfspot-884c9',
    storageBucket: 'surfspot-884c9.firebasestorage.app',
    iosBundleId: 'com.example.surfspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDudk0G-cvMu10HEy2o7Brt7cDI8XvmjTU',
    appId: '1:37223953098:web:eff456ce1c7b6b7b113a33',
    messagingSenderId: '37223953098',
    projectId: 'surfspot-884c9',
    authDomain: 'surfspot-884c9.firebaseapp.com',
    storageBucket: 'surfspot-884c9.firebasestorage.app',
  );
}
